### ISSUE TITLE
bruh drop this bullshit

### ISSUE THREAD

**Issue by ghost** [tandpfun/DisableTokens#3]
yes companies like glitch have too many discord bot tokens but by doing this you disable bots please stop

**Comment by tandpfun** [comment]
What? Put your token in the env file!! If someone else had found your token, they could have used it to hack your bot and ban a ton of members, get the bot banned from discord, or your user account. Please secure your token inside the .env file if you do not want your bot to be hacked.

**Comment by tandpfun** [comment]
Again, I'm not hacking bots. I'm preventing the bots from being hacked.

**Comment by tandpfun** [comment]
In addition, I'm not going to search the same project twice. So, if you want to risk your token being hacked, just regenerate the token and put it right back where it was before. If not, follow the steps in the discord server on how to secure your token inside the env file.

**Comment by ghost** [comment]
I didn't say you hacked bots I just want to say what you do can worry people but you inform people with what you do, interesting
(I'm not idiot my bots working private projects)
