### ISSUE TITLE
Better ways than publicising tokens

### ISSUE THREAD

**Issue by nenkoszai** [tandpfun/DisableTokens#6]
You could had just emailed to discord privately about the leaked tokens and they would had invalidated the tokens. 
When discord invalidate tokens, they will always inform the bot developer with the reason why. 

Your way of approach allows bad actors to compromise the token before discord own bot manage to datamine your published token leaks. Their bot doesnt always scan instantanously and that headroom allows bad actors to do very dangerous things to compromised bots. 

You try to say you want to inform the public but you also allow bad actors to subscribe to your  repo and try to do as much damage as possible.

What you are doing now is extremely dumb and dangerous.

**Comment by tandpfun** [comment]
I never considered that. I'll be sure to email next time, and then upload em for services like bots.gg to scrape for leaked tokens. Thank you for notifying me of this.

**Comment by A5rocks** [comment]
https://docs.github.com/en/developers/overview/secret-scanning I'm pretty sure Discord uses this -- it's probably not a bot that constantly watches GitHub :p

**Comment by tandpfun** [comment]
Yea, but it does take time to deactivate all the tokens. If someone started at the bottom and used all those tokens before they were deactivated, they could cause a lot of damage
